download_url: https://galaxy.ansible.com/download/infra-controller_configuration-2.3.1.tar.gz
format_version: 1.0.0
name: controller_configuration
namespace: infra
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.3.1
version_url: https://galaxy.ansible.com/api/v2/collections/infra/controller_configuration/versions/2.3.1/
